---
base_dir: '.\dataset\CHI\'
file_name : 'crime_CHI.csv'
city: 'CHI'

data:
  batch_size: 32
  dataset_dir: CRIME-CHI/8
  test_batch_size: 32
  val_batch_size: 32
  chunk_size: 10

model:
  seed: 42
  cl_decay_steps: 2000
  horizon: 1
  input_dim: 616
  num_nodes: 77
  num_layers: 1
  output_dim: 616
  hidden_units: 16
  tower_hidden_units: 16
  dropout_rate: 0.3
  kernel_size: 3
  e1_size : 77
  e2_size : 25
  e3_size :  16

train:
  city: 'CHI'
  num_nodes: 77
  output_dim: 616
  base_lr: 0.001
  dropout: 0
  epochs: 100
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 50
  steps: [20, 30, 40, 50]
  test_every_n_epochs: 10